name: Admin CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted, frontend]

    defaults:
      run:
        working-directory: ./admin
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

      - name: USE NODEJS ${{ matrix.node-version }} - ${{ matrix.architecture }}
        uses: actions/setup-node@v2

      # - name: INSTALL PROJECT DEPENDENCIES
      #   run: npm install

      - name: Execute our script
        run: sudo chmod +x frontend_admin.sh && ./frontend_admin.sh
